# Generated by Django 5.0.6 on 2024-06-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AWS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('engine', models.CharField(max_length=100)),
                ('storage', models.IntegerField()),
                ('region', models.CharField(max_length=100)),
                ('endpoint', models.CharField(max_length=255)),
                ('creation_time', models.DateTimeField()),
                ('aws_access_key_id', models.CharField(max_length=255)),
                ('aws_secret_access_key', models.CharField(max_length=255)),
                ('db_instance_identifier', models.CharField(max_length=100)),
                ('master_username', models.CharField(max_length=100)),
                ('master_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='AWSInstance',
        ),
    ]
