# Generated by Django 5.0.6 on 2024-07-05 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AWS', '0003_databaseinstance_delete_database'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DatabaseInstance',
        ),
    ]
